export enum Stage {
    Case1 = 1,
    Case2 = 2,
    Case3 = 3,
    Case4 = 4,
    Case5 = 5,
    Case6 = 6,
    Case7 = 7,
    Case8 = 8,
    Case9 = 9,
    Case10 = 10,
    Case11 = 11,
    Case12 = 12,
    Case13 = 13,
    Case14 = 14
}

export const StageMessages: Record<Stage, { title: string; message: string }> = {
    [Stage.Case1]: { title: 'DEMANDA - Inicio del Juicio', message: 'Luego se formula una presentación compleja, en la cual se consignan todos los datos de la relación laboral, su finalización y la conducta asumida por la empresa posterior, se indica las normas legales que se aplican al caso, realizando incluso una cronología para detallar como se integran las distintas leyes, resoluciones, convenios colectivos de trabajo, fundamentando la petición, incluso con cita de juicios anteriores en los que existe similitud de situaciones ya tratadas por otros jueces y con resultados como los que buscamos.- Este lapso suele demorar 2 meses.' },
    [Stage.Case2]: { title: 'AMPLIACIÓN DE DEMANDA', message: 'En virtud de las modificaciones perjudiciales de las condiciones de los trabajadores de Call Centers, pactadas por el sindicato de comercio, se formula una impugnación, separada de la presentación anterior, de forma de resaltar el contraste y dejar plasmado, de forma clara, el perjuicio y la consecuente ilegalidad de dicho acuerdo.' },
    [Stage.Case3]: { title: 'CUMPLIMIENTO DE RECAUDOS', message: 'Luego del análisis por parte del juez, éste requerirá que presentemos toda la documentación que Citamos en la DEMANDA, conjuntamente con cualquier otro dato y / o comprobante que considere necesario para un mejor entendimiento del caso.' },
    [Stage.Case4]: { title: 'TRASLADO DE DEMANDA', message: 'El juez pone en conocimiento de la empresa que se le inició un juicio, de qué características es, qué se pide, con qué fundamento, para que la empresa se defienda, normalmente rechazando todo lo que se solicita. Esta defensa por parte de la empresa es lo que es conoce como CONTESTACION DE DEMANDA.' },
    [Stage.Case5]: { title: 'DOCUMENTACIÓN DE LA EMPRESA', message: 'El juez concede un plazo a la empresa para la presentación de toda la documentación de la que intentará valerse, a los fines de resistir el reclamo que se le inició en su contra. Hasta aquí transcurrieron 4 a 6 meses.' },
    [Stage.Case6]: { title: 'APERTURA A PRUEBAS', message: 'Luego de analizar el planteo formulado por la empresa, la documentación presentada, determinar los hechos controvertidos, es decir aquellos sobre los que no estamos de acuerdo, podemos solicitar la Apertura a Pruebas, para que el juez nos otorgue a todos (tanto a quien reclama, como a quién se le reclama), un plazo para indicar qué pruebas utilizaremos para demostrar que los hechos que citamos en la DEMANDA y que la empresa rechazó EN LA CONTESTACION DE DEMANDA.' },
    [Stage.Case7]: { title: 'AUDIENCIA DE CONCILIACIÓN', message: 'Luego de que se ofrecieron todas las pruebas, las mismas se reservan para ser producidas con posterioridad. Previo a seguir avanzando, el juez establecerá una fecha (a veces muy lejana) para el desarrollo de una audiencia, con el fin de poder conocer más allá de la postura asumida por las partes en la DEMANDA Y CONTESTACION DE DEMANDA, así puede analizar si existe una posibilidad de llegar a un acuerdo y evitar que se avance un juicio quizás por falta de diálogo y no porque realmente exista una diferencia insalvable. En la actualidad las empresas de Calls Centers NO realizan ofrecimientos, por lo que pierde sentido la participación en dicha audiencia, sin embargo el juez debe desarrollarla sí o sí, aun sin participación de las partes.- El lapso transcurrido hasta aquí es muy variable, pero suele rondar los 8 meses.' },
    [Stage.Case8]: {
        title: 'INICIAN LAS PRUEBAS',
        message: `En la audiencia citada precedentemente, el juez establecerá cuándo se iniciará con la producción de las pruebas que ofrecimos con anterioridad a dicha audiencia. En la fecha señalada por el juez (algunos juzgados establecen un plazo de hasta 4 meses entre la audiencia y el inicio de la producción de las pruebas) ordena que se produzan las pruebas ofrecidas por las partes, por ejemplo: 
            a.- Se ordena a los organismos que remitan los INFORMES solicitados al correo que indique si los telegramas y cartas documentos que se presentaron en el expediente son auténticos, es decir no se encuentran falsificados, cuál fue la fecha en la que se despachó, la fecha en la que se entregó al destinatario, o en su defecto la razón por la cual no llegó a destino. Se solicita INFORMES al Seoc para que indique cuáles fueron las escalas salariales que debió cumplir la empresa, también el Call solicita que presenten los convenios que firmaron para reducir los salarios de los trabajadores. Se solicita INFORMES a la Secretaría de Trabajo, al Ministerio de Trabajo, a la Cámara Argentina de Call Centers, para que también envíen copias de los convenios firmados por el sindicato de comercio, las resoluciones de los organismos públicos aprobando esos convenios, etc.
            b.- Se fijan las fechas de audiencias de testigos (pueden haber sido necesarios o no, pueden haber sido ofrecidos testigos por la empresa, por el trabajador, o nadie ofreció testigos), usualmente se necesitan en los despidos con causa.
            c.- Se fijan las fechas para la impugnación de documentación por parte del trabajador, en caso de que no hubiera firmado lo presentado por la empresa y ésta hubiera falsificado su firma, o no hubiera recibido las cartas documentos que le remitió el Call, o no hubiera tenido conocimiento de los sumarios iniciados, etc.
            d.- Se sortean los peritos que van a intervenir en el caso (normalmente contadores para que revisen la planilla presentada por el trabajador para determinar el monto reclamado, verificar los libros y registros de la empresa para constatar la existencia de los pagos que citaron, para que formule su propia planilla de lo que le corresponde al trabajador, o peritos informáticos, para que verifiquen los sistemas de la empresa y determinen si existieron las gestiones, si las mismas fueron realizadas por el trabajador, en qué fecha, con qué usuario, en qué consistieron, etc. Como se advierte es una etapa muy compleja, que lleva gran parte del tiempo del reclamo, por lo que suele demorar 3, 4 meses o incluso mucho más, ya que depende de factores externos como ser la intervención de otros organismos, o profesionales ajenos al juicio, incluso de la disponibilidad del juzgado en su agenda, para fijar las fechas de audiencias. Hasta la finalización de esta etapa transcurrieron 10 a 11 meses.`
    },
    [Stage.Case9]: {
        title: 'ALEGATOS Y PRIMERA SENTENCIA',
        message: 'Los alegatos son presentaciones que formulan las partes en un juicio (reclamante trabajador y reclamado empresa), vinculando lo que dijeron en la DEMANDA Y CONTESTACIÓN DE DEMANDA, con lo acreditado mediante la producción de las pruebas. El juez también le da una opinión al Agente Fiscal, ya que se cuestiona la aplicación, validez y constitucionalidad de normas que pueden tener efectos en otras personas ajenas al juicio. Posteriormente, el juez tomará el expediente, con todas las constancias que se formularon durante el proceso desarrollado hasta aquí, para dictar su SENTENCIA. La sentencia contendrá un relato de los hechos del caso, de las pruebas que se produjeron, formulará su propia consideración de la normativa aplicable y de la manera en la que se aplicará, emitiendo una decisión sobre lo que corresponde que el Call les pague. Esto será un monto en pesos Argentinos, compuesto de lo que la empresa les adeudaba al momento de la desvinculación (Capital), más intereses desde la desvinculación y hasta la fecha de dictado de la sentencia. Hasta aquí transcurrieron 14 meses.'
    },
    [Stage.Case10]: { title: 'APELACIÓN', message: 'La parte (reclamante trabajador y empresa reclamado) que no se encuentre conforme con la sentencia, presentará un recurso de apelación en contra de esa sentencia, para solicitar que otros jueces distintos al que ya emitió la PRIMERA SENTENCIA , revisen el caso, ésta primera sentencia y dicten una SEGUNDA SENTENCIA, este proceso se encuentra cargado de muchísimos trámites en los que interviene principalmente el primer juez, y la necesidad de estar seguros que el expediente se envió completo, con todas las pruebas, la documentación, que no existe objeción en contra de los jueces que van a intervenir, también es la da la posibilidad que emita opinión el Agente Fiscal de Cámara, por lo que usualmente el trámite del dictado de la Sentencia de Apelación (SEGUNDA SENTENCIA) suele demorar 8 meses hábiles.- Hasta el dictado de la segunda sentencia transcurrieron 22 meses.' },
    [Stage.Case11]: { title: 'RECURSO DE CASACIÓN LOCAL', message: 'Una vez que se cuenta con la segunda sentencia, existe la posibilidad de que la parte que nos está de acuerdo con esta segunda sentencia, solicite que la Corte Suprema de Justicia de Tucumán, que está integrada por otros jueces distintos, la revise y dicte una TERCERA SENTENCIA, lo cual también tiene una demora excesiva y aproximada de 8 meses.- Hasta el dictado de esta sentencia transcurrieron 30 meses.' },
    [Stage.Case12]: { title: 'RECURSO DE CASACIÓN NACIONAL', message: 'Nuevamente existe la posibilidad, esta vez como última oportunidad, de que una de las partes (reclamante o reclamado), solicite que Otros jueces, esta vez los máximos jueces del País, revisen la Tercera sentencia (lo que implica una revisión de la segunda y de la primera también), emitiendo una CUARTA SENTENCIA, lo que terminará en una solución definitiva del caso.' },
    [Stage.Case13]: { title: 'SENTENCIA FIRME - CUMPLIMIENTO', message: 'Cuando tenemos sentencia firme, es decir cuando ya no existe la posibilidad de que se solicite una nueva revisión (lo cual puede suceder luego de alguna de las sentencias, ya sea la primera, la segunda o la tercera), ya sea porque se venció el plazo para presentar un recurso, o porque el juez que dictó la sentencia no permite que se envíe el expediente para la revisión de su sentencia, se procede al cumplimiento, es decir se le otorga un plazo final a la empresa para que cumpla, en caso de que no lo haga se ordena el pago con el dinero que previamente se embargó, es decir con el dinero que ya se sacó de las cuentas de la empresa (lo hacemos una vez que se dicta la primera sentencia, para asegurar que cuando tengamos una decisión firme se encuentre garantizado su cumplimiento) se ordena el pago al trabajador, a través del Banco Macro, por ventanilla o bien por transferencia a la cuenta personal del trabajador (en este último caso el trabajador asume el riesgo de una retención por parte de su banco, en concepto del Impuesto Provincial de Ingresos Brutos). ¿Qué monto es el que estaría cobrando en este caso el trabajador? El que se determinó en la PRIMERA SENTENCIA. ¿Qué sucede con la devaluación que sufrió ese monto?' },
    [Stage.Case14]: { title: 'INTERESES', message: 'Luego del pago de la primera sentencia, la cual incluye el monto adeudado por la empresa al momento de la desvinculación y hasta la fecha de dictado de la PRIMERA SENTENCIA, se presenta una planilla de intereses que va a compensar la devaluación entre la fecha de la primera sentencia (último día de intereses ya pagados) y la fecha del pago.Esta presentación es contestada por la empresa, para que el juez, luego de haber escuchado a ambas partes, pueda dictar una resolución estableciendo cuál es el monto de los intereses que le corresponden al trabajador. Una vez que contamos con el monto de intereses aprobados por el juez, se procede a embargar ese dinero (solicitar que el juez ordene que el banco X quite de la cuenta bancaria de la empresa dicho monto y lo transfiera a una cuenta judicial, a nombre del juicio). Una vez acreditado ese dinero, se solicita la orden de pago y se repite un proceso similar al primer pago.' }
};

